setwd("/path/to/VAEN/Figure/FigureS4/")

pca.info  = read.table("../../main/RANK.nonVAE/PCA/dr.CCLE/01/PCA.CCLE.07292020.txt", as.is=T, header=T)
expr.info = read.table("../../main/RANK.nonVAE/EXPR/dr.CCLE/01/EXPR.CCLE.txt", as.is=T, header=T)
info = read.table("VAE.best.info.txt", header=T, as.is=T)  ### generated by VAEN.model_summary.R
load("info.RData")  ### generated by VAEN.model_summary.R

in_sample_PCC = c()
for(drug in colnames(all.in_sample_R2.mat)){
	in_sample_PCC = rbind(in_sample_PCC, cbind(drug, c(1:100), all.in_sample_R2.mat[, drug], grp="VAEN") )
}

in_sample_PCC = rbind(in_sample_PCC, cbind(info[,1], rep(1, nrow(info)), info[, 4], grp="VAEN_selected") )
in_sample_PCC = rbind(in_sample_PCC, cbind(pca.info[,1], rep(1, nrow(pca.info)), pca.info[, 3], grp="PCA+EN") )
in_sample_PCC = rbind(in_sample_PCC, cbind(expr.info[,1], rep(1, nrow(expr.info)), expr.info[, 3], grp="Gene+EN") )


dat4plot = as.data.frame(in_sample_PCC)
dat4plot[,3] = as.numeric(as.character(dat4plot[,3]))

dat4plot[,4] <- factor(dat4plot[,4], levels = c("VAEN", "VAEN_selected", "PCA+EN", "Gene+EN"))


p1 = ggplot(dat4plot, aes(x=drug, y=V3, fill=grp)) + geom_boxplot(fill="white",aes(colour=grp)) + 
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("In sample PCC")

###########################################################################################################################################

CV_R2 = c()
for(drug in colnames(all.avg_CV_R2.mat)){
	CV_R2 = rbind(CV_R2, cbind(drug, c(1:100), all.avg_CV_R3.mat[, drug], grp="VAEN") )
}

CV_R2 = rbind(CV_R2, cbind(info[,1], rep(1, nrow(info)), info[, 6], grp="VAEN_selected") )
CV_R2 = rbind(CV_R2, cbind(pca.info[,1], rep(1, nrow(pca.info)), pca.info[, 5], grp="PCA+EN") )
CV_R2 = rbind(CV_R2, cbind(expr.info[,1], rep(1, nrow(expr.info)), expr.info[, 5], grp="Gene+EN") )

dat4plot = as.data.frame(CV_R2)
dat4plot[,3] = as.numeric(as.character(dat4plot[,3]))

dat4plot[,4] <- factor(dat4plot[,4], levels = c("VAEN", "VAEN_selected", "PCA+EN", "Gene+EN"))


p2 = ggplot(dat4plot, aes(x=drug, y=V3, fill=grp)) + geom_boxplot(fill="white",aes(colour=grp)) + 
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("CV R2")

pdf("S4.A.compare.pdf", width=10)
multiplot(plotlist=list(p1, p2), layout=matrix(1:2, nrow=2))
dev.off()

###########################################################################################################################################

pca.self = read.delim("/path/to/VAEN/main/RANK.nonVAE/PCA/dr.CCLE/01/PCA.A.shared.drugs.ori.cor.07292020.txt", header=T, as.is=T)
pca.self = pca.self[, c(1,2,3,7,6)]

expr.self = read.delim("/path/to/VAEN/main/RANK.nonVAE/EXPR/dr.CCLE/01/EXPR.A.shared.drugs.ori.cor.txt", header=T, as.is=T)
expr.self = expr.self[, c(1,2,3,7,6)]

vae.A.best.self = read.delim("../Figure2/Figure2C.txt", header=T, as.is=T)
vae.A.each.self = read.delim("A.each.shared.drugs.ori.cor.txt", header=T, as.is=T)  ### generated by VAEN.model_summary.each.R

self.cor = c()
for(drug in pca.self[,1]){
	which(vae.A.each.self[,1]==drug) -> ii
	self.cor = rbind(self.cor, cbind(drug, c(1:100), vae.A.each.self[ii, 7], grp="VAEN") )
}

self.cor = rbind(self.cor, cbind(vae.A.best.self[,1], rep(1, nrow(vae.A.best.self)), vae.A.best.self[, 7], grp="VAEN_selected") )
self.cor = rbind(self.cor, cbind(pca.self[,1], rep(1, nrow(pca.self)), pca.self[, 4], grp="PCA+EN") )
self.cor = rbind(self.cor, cbind(expr.self[,1], rep(1, nrow(expr.self)), expr.self[, 4], grp="Gene+EN") )

dat4plot = as.data.frame(self.cor)
dat4plot[,3] = as.numeric(as.character(dat4plot[,3]))

dat4plot[,4] <- factor(dat4plot[,4], levels = c("VAEN", "VAEN_selected", "PCA+EN", "Gene+EN"))


p3 = ggplot(dat4plot, aes(x=drug, y=V3, fill=grp)) + geom_boxplot(fill="white",aes(colour=grp)) + 
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("PCC in cell lines")


##############
pca.tcga = read.delim("/path/to/VAEN/main/RANK.nonVAE/PCA/dr.CCLE/01/PCA.A.shared.drugs.pred.cor.07292020.txt", header=T, as.is=T)
expr.tcga = read.delim("/path/to/VAEN/main/RANK.nonVAE/EXPR/dr.CCLE/01/EXPR.A.shared.drugs.pred.cor.txt", header=T, as.is=T)

vae.A.best.tcga = read.delim("../Figure2/Figure2B.txt", header=T, as.is=T)
vae.A.each.tcga = read.delim("A.each.shared.drugs.pred.cor.txt", header=T, as.is=T)  ### generated by VAEN.model_summary.each.R

tcga.cor = c()
for(drug in pca.tcga[,1]){
	which(vae.A.each.tcga[,1]==drug) -> ii
	tcga.cor = rbind(tcga.cor, cbind(drug, c(1:100), vae.A.each.tcga[ii, 4], grp="VAEN") )
}

tcga.cor = rbind(tcga.cor, cbind(vae.A.best.tcga[,1], rep(1, nrow(vae.A.best.tcga)), vae.A.best.tcga[, 4], grp="VAEN_selected") )
tcga.cor = rbind(tcga.cor, cbind(pca.tcga[,1], rep(1, nrow(pca.tcga)), pca.tcga[, 4], grp="PCA+EN") )
tcga.cor = rbind(tcga.cor, cbind(expr.tcga[,1], rep(1, nrow(expr.tcga)), expr.tcga[, 4], grp="Gene+EN") )

dat4plot = as.data.frame(tcga.cor)
dat4plot[,3] = as.numeric(as.character(dat4plot[,3]))

dat4plot[,4] <- factor(dat4plot[,4], levels = c("VAEN", "VAEN_selected", "PCA+EN", "Gene+EN"))


p4 = ggplot(dat4plot, aes(x=drug, y=V3, fill=grp)) + geom_boxplot(fill="white",aes(colour=grp)) + 
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("PCC in TCGA")

pdf("S4.B.compare.shared.pdf", width=10)
multiplot(plotlist=list(p3, p4), layout=matrix(1:2, nrow=2))
dev.off()

