### For Figure 3A

setwd("/work/Figures/Figure3")

load("/work/result.EN/dr.CCLE/01/F1-W5-PCC.info.RData")  ### this file is generated by /work/code/01.02.CCLE.final.R
anno = read.csv("/work/data/CCLE/CCLE_NP24.2009_Drug_data_2015.02.24.csv", as.is=T)
drugs = sort(unique(anno$Compound))

#####################
dr.ccle.mat = c()
for(kdrug in 1:length(drugs)){
	drug = drugs[kdrug]
	if(drug == "X17.AAG")drug = "17-AAG"
	gsub("\\.", "-", drug) -> drug
	tmp = cbind(idx = c(1:100), all.F1_R2.mat[, drug], all.in_sample_R2.mat[, drug], all.avg_CV_R2.mat[, drug] )
	tmp = tmp[order(tmp[,4], decreasing=T),]
	best.index = tmp[1,1]
	
	load( paste("/work/result.EN/dr.CCLE/01/", best.index ,".CCLE.model.list.RData", sep="") )  ### these files are generated by /work/code/01.01.CCLE.EN_GLM.R
	model.list[[ drug ]] -> res.list
	Ys = res.list$Ys
	
	which(Ys[,1]!=-9) -> ii
	Ys = Ys[ii, ]
	dr.ccle.mat = rbind(dr.ccle.mat, cbind(drug = drug, sample = rownames(Ys), ActArea = Ys[,1], grp="CCLE Observed DR") )
	dr.ccle.mat = rbind(dr.ccle.mat, cbind(drug = drug, sample = rownames(Ys), ActArea = Ys[,2], grp="CCLE Predicted DR") )
}

#save(dr.ccle.mat, file="dr.ccle.mat.RData")


new.mat = as.data.frame(dr.ccle.mat)
rownames(new.mat) = NULL
new.mat[,3] = as.numeric(as.character(new.mat[,3]))

pdf("3A-CCLE.pdf", width=10, height=5)
ggplot(aes(y = ActArea, x = drug, fill = grp), data = new.mat) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = c(0.9, 0.9)) + 
  xlab("") + ylab("Drug response (ActArea)") +
  guides(fill=guide_legend(title=""))
  
dev.off()
