#setwd("/path/to/VAEN/Figure/FigureS13")

### generated by ../Figure7/7A.01.R
load("../Figure7/MC3.RData")

######################################################################

drug.ccle = read.table(file="../../result.EN/dr.GDSC/VAEN_GDSC.A.pred_TCGA.txt", header=T, as.is=T, sep="\t")
colnames(drug.ccle)[3:ncol(drug.ccle)] -> drugs
cancer.types = unique(drug.ccle[,2])
sample.type = substr(drug.ccle[,1], 14, 15)
ss = gsub("\\.", "-", drug.ccle[,1])
drug.ccle[,1] = ss

######################################################################
info = c()
gene.drug.limma.mat = c()
for(ct in 1:length(cancer.types)){
	cancer = cancer.types[ct]
	if(cancer == "BRCA" | cancer == "LGG" | cancer == "THCA")next
	mut.list = cancer.mutation.list[[ cancer ]]
	new.mut.mat.3cols = mut.list[[ "mut_wo_indel" ]]
	fixed.ss = mut.list[[ "ss"  ]]
	gene2WT.list = mut.list[[ "gene2WT.list" ]]
	
	type.code = "01"
	if(cancer == "LAML"){ type.code = "03" }
	if(cancer == "SKCM"){ type.code = "06" }
	
	blca.ccle = drug.ccle[match(fixed.ss, drug.ccle[,1]),]
	apply(blca.ccle[, 3:ncol(blca.ccle)], 2, as.numeric) -> new.ccle
	
	tapply(new.mut.mat.3cols[,2], new.mut.mat.3cols[,1], function(u)length(unique(u))) -> gene2ss
	candidate.genes = sort(names(gene2ss[which(gene2ss >= 10)]))
	print(paste(cancer, length(candidate.genes), nrow(blca.ccle), sep=" "))
	if(length(candidate.genes) < 1)next
	info = rbind(info, c(cancer, length(candidate.genes)))
	
	for(kgene in 1:length(candidate.genes)){
		ii = which(new.mut.mat.3cols[, 1] == candidate.genes[kgene])
		MT.ss = unique(new.mut.mat.3cols[ii, 2])
		match(MT.ss, fixed.ss) -> MT.ii
		
		WT.ss = gene2WT.list[[ candidate.genes[kgene] ]]
		match(WT.ss, fixed.ss) -> WT.ii
		
		apply(new.ccle, 2, function(u){
			wilcox.test(u[MT.ii], u[WT.ii])$p.value
		}) -> ps.twosided
		
		apply(new.ccle, 2, function(u){
			mean(u[MT.ii], na.rm=T)-mean(u[WT.ii], na.rm=T) 
		}) -> fcs
		
		gene.drug.limma.mat = rbind(gene.drug.limma.mat, cbind(cancer, candidate.genes[kgene], drugs, ps.twosided, fcs, length(MT.ss), length(MT.ss)/nrow(blca.ccle) ))
	}
}

### LGG
cancer = "LGG"
mut.list = cancer.mutation.list[[ cancer ]]
new.mut.mat.3cols = mut.list[[ "mut_wo_indel" ]]
fixed.ss = mut.list[[ "ss"  ]]
gene2WT.list = mut.list[[ "gene2WT.list" ]]

subtype = read.delim("../../DATA/LGG.subtype.TCGA.txt", as.is=T, header=T)
ss = substr(fixed.ss, 1, 12)
subtype[which(subtype[,9]=="coc1"),1] -> g1
subtype[which(subtype[,9]=="coc2"),1] -> g2
subtype[which(subtype[,9]=="coc3"),1] -> g3
subtype.list = list()
subtype.list[["LGG-coc1"]] = g1
subtype.list[["LGG-coc2"]] = g2
subtype.list[["LGG-coc3"]] = g3
	
for(k in 1:length(subtype.list)){
	cancer = names(subtype.list)[k]
	subtype.ss = subtype.list[[k]]
	substr(new.mut.mat.3cols[,2], 1, 12) -> new.mut.mat.3cols.ss
	subtype.mut.mat = new.mut.mat.3cols[new.mut.mat.3cols.ss %in% subtype.ss, ]
	fixed.ss = unique(subtype.mut.mat[,2])
	
	tapply(subtype.mut.mat[,2], subtype.mut.mat[,1], function(u)length(unique(u))) -> gene2ss
	candidate.genes = sort(names(gene2ss[which(gene2ss >= 10)]))
	
	blca.ccle = drug.ccle[match(fixed.ss, drug.ccle[,1]),]
	apply(blca.ccle[, 3:ncol(blca.ccle)], 2, as.numeric) -> new.ccle
	print(paste(cancer, length(candidate.genes), nrow(blca.ccle), sep=" "))
	if(length(candidate.genes) < 1)next
	info = rbind(info, c(cancer, length(candidate.genes)))
	
	for(kgene in 1:length(candidate.genes)){
		ii = which(subtype.mut.mat[, 1] == candidate.genes[kgene])
		MT.ss = unique(subtype.mut.mat[ii, 2])
		match(MT.ss, fixed.ss) -> MT.ii
		
		WT.ss = intersect(gene2WT.list[[ candidate.genes[kgene] ]], fixed.ss)
		match(WT.ss, fixed.ss) -> WT.ii
		
		apply(new.ccle, 2, function(u){
			wilcox.test(u[MT.ii], u[WT.ii])$p.value
		}) -> ps.twosided
		
		apply(new.ccle, 2, function(u){
			mean(u[MT.ii], na.rm=T)-mean(u[WT.ii], na.rm=T) 
		}) -> fcs
		
		gene.drug.limma.mat = rbind(gene.drug.limma.mat, cbind(cancer, candidate.genes[kgene], drugs, ps.twosided, fcs, length(MT.ss), length(MT.ss)/nrow(blca.ccle) ))
	}
}

### BRCA
cancer = "BRCA"
mut.list = cancer.mutation.list[[ cancer ]]
new.mut.mat.3cols = mut.list[[ "mut_wo_indel" ]]
fixed.ss = mut.list[[ "ss"  ]]
gene2WT.list = mut.list[[ "gene2WT.list" ]]

subtype = read.delim("../../DATA/BRCA.subtype.TCGA.txt", as.is=T, header=T, sep="\t", skip=1)
ss = substr(fixed.ss, 1, 12)
subtype[which(subtype$PAM50.mRNA=="Basal-like"),1] -> g1
subtype[which(subtype$PAM50.mRNA=="HER2-enriched"),1] -> g2
subtype[which(subtype$PAM50.mRNA=="Luminal A"),1] -> g3
subtype[which(subtype$PAM50.mRNA=="Luminal B"),1] -> g4
subtype.list = list()
subtype.list[["BRCA-Basal"]] = g1
subtype.list[["BRCA-HER2"]] = g2
subtype.list[["BRCA-LumA"]] = g3
subtype.list[["BRCA-LumB"]] = g4

for(k in 1:length(subtype.list)){
	cancer = names(subtype.list)[k]
	subtype.ss = subtype.list[[k]]
	substr(new.mut.mat.3cols[,2], 1, 12) -> new.mut.mat.3cols.ss
	subtype.mut.mat = new.mut.mat.3cols[new.mut.mat.3cols.ss %in% subtype.ss, ]
	fixed.ss = unique(subtype.mut.mat[,2])
	
	tapply(subtype.mut.mat[,2], subtype.mut.mat[,1], function(u)length(unique(u))) -> gene2ss
	candidate.genes = sort(names(gene2ss[which(gene2ss >= 10)]))
	
	blca.ccle = drug.ccle[match(fixed.ss, drug.ccle[,1]),]
	apply(blca.ccle[, 3:ncol(blca.ccle)], 2, as.numeric) -> new.ccle
	print(paste(cancer, length(candidate.genes), nrow(blca.ccle), sep=" "))
	if(length(candidate.genes) < 1)next
	info = rbind(info, c(cancer, length(candidate.genes)))
	
	for(kgene in 1:length(candidate.genes)){
		ii = which(subtype.mut.mat[, 1] == candidate.genes[kgene])
		MT.ss = unique(subtype.mut.mat[ii, 2])
		match(MT.ss, fixed.ss) -> MT.ii
		
		WT.ss = intersect(gene2WT.list[[ candidate.genes[kgene] ]], fixed.ss)
		match(WT.ss, fixed.ss) -> WT.ii
		
		apply(new.ccle, 2, function(u){
			wilcox.test(u[MT.ii], u[WT.ii])$p.value
		}) -> ps.twosided
		
		apply(new.ccle, 2, function(u){
			mean(u[MT.ii], na.rm=T)-mean(u[WT.ii], na.rm=T) 
		}) -> fcs
		
		gene.drug.limma.mat = rbind(gene.drug.limma.mat, cbind(cancer, candidate.genes[kgene], drugs, ps.twosided, fcs, length(MT.ss), length(MT.ss)/nrow(blca.ccle) ))
	}
}

### THCA
cancer = "THCA"
mut.list = cancer.mutation.list[[ cancer ]]
new.mut.mat.3cols = mut.list[[ "mut_wo_indel" ]]
fixed.ss = mut.list[[ "ss"  ]]
gene2WT.list = mut.list[[ "gene2WT.list" ]]

subtype = read.delim("../../DATA/THCA.BRS.txt", as.is=T, header=F, sep="\t")
ss = substr(subtype[,1], 1, 15)
ss[which(subtype[,2]=="Braf-like")] -> g1
ss[which(subtype[,2]=="Ras-like")] -> g2
subtype.list = list()
subtype.list[["THCA-Braf-like"]] = g1
subtype.list[["THCA-Ras-like"]] = g2

for(k in 1:length(subtype.list)){
	cancer = names(subtype.list)[k]
	subtype.ss = subtype.list[[k]]
	subtype.mut.mat = new.mut.mat.3cols[new.mut.mat.3cols[,2] %in% subtype.ss, ]
	fixed.ss = unique(subtype.mut.mat[,2])
	
	tapply(subtype.mut.mat[,2], subtype.mut.mat[,1], function(u)length(unique(u))) -> gene2ss
	candidate.genes = sort(names(gene2ss[which(gene2ss >= 10)]))
	
	blca.ccle = drug.ccle[match(fixed.ss, drug.ccle[,1]),]
	apply(blca.ccle[, 3:ncol(blca.ccle)], 2, as.numeric) -> new.ccle
	print(paste(cancer, length(candidate.genes), nrow(blca.ccle), sep=" "))
	if(length(candidate.genes) < 1)next
	info = rbind(info, c(cancer, length(candidate.genes)))
	
	for(kgene in 1:length(candidate.genes)){
		ii = which(subtype.mut.mat[, 1] == candidate.genes[kgene])
		MT.ss = unique(subtype.mut.mat[ii, 2])
		match(MT.ss, fixed.ss) -> MT.ii
		
		WT.ss = intersect(gene2WT.list[[ candidate.genes[kgene] ]], fixed.ss)
		match(WT.ss, fixed.ss) -> WT.ii
		
		apply(new.ccle, 2, function(u){
			wilcox.test(u[MT.ii], u[WT.ii])$p.value
		}) -> ps.twosided
		
		apply(new.ccle, 2, function(u){
			mean(u[MT.ii], na.rm=T)-mean(u[WT.ii], na.rm=T) 
		}) -> fcs
		
		gene.drug.limma.mat = rbind(gene.drug.limma.mat, cbind(cancer, candidate.genes[kgene], drugs, ps.twosided, fcs, length(MT.ss), length(MT.ss)/nrow(blca.ccle) ))
	}
}

############################################################################################
colnames(gene.drug.limma.mat) = c("Cancer", "Gene", "Drug", "p.twosided", "FC", "nMut", "nMutProp")

load("../../DATA/ncbiRefSeq.01252019.hg19.gene2ll.RData")
long.genes = names(gene2ll[gene2ll > 200000])
gene.drug.limma.mat = gene.drug.limma.mat[!gene.drug.limma.mat[,2] %in% long.genes, ]

write.table(gene.drug.limma.mat, file="FigureS13.A.txt", row.names=F, quote=F, sep="\t")
gene.drug.limma.mat = read.table("FigureS13.A.txt", as.is=T, header=T)

###### *****
gene.drug.limma.mat$adjp = NULL
drugs = unique(gene.drug.limma.mat[,3])
for(k in 1:length(drugs)){
	which(gene.drug.limma.mat[,3] == drugs[k]) -> ii
	p.adjust(gene.drug.limma.mat[ii,4], method="BH") -> adjp
	gene.drug.limma.mat[ii, "adjp"] = adjp
}
###### *****

which(gene.drug.limma.mat$adjp < 0.05 & gene.drug.limma.mat$FC > 0) -> ii.1
which(gene.drug.limma.mat$adjp < 0.05 & gene.drug.limma.mat$FC < 0) -> ii.2
cc = rep(0, nrow(gene.drug.limma.mat)); cc[ii.1] = 2; cc[ii.2] = 1
gene.drug.limma.mat$color = as.factor(cc)

write.table(gene.drug.limma.mat, file="FigureS13.A.txt", row.names=F, quote=F, sep="\t")

